name: run-tests

on: push

jobs:
    win:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
        - uses: msys2/setup-msys2@v2
          with:
              msystem: MINGW64
              install: >-
                  make
                  mingw-w64-x86_64-python
                  mingw-w64-x86_64-cmake
                  mingw-w64-x86_64-gcc
                  mingw-w64-x86_64-boost
        - uses: actions/checkout@v2
        - name: Compile
          run: |
              ./acprep opt make
        - name: Test
          run: |
              make test
