name: run-tests

on: push

jobs:
    win:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
        - uses: msys2/setup-msys2@v2
          with:
              update: true
              install: >-
                  base-devel
                  git
                  mingw-w64-x86_64-cmake
                  mingw-w64-x86_64-make
                  mingw-w64-x86_64-boost
                  mingw-w64-x86_64-gcc
        - uses: actions/checkout@v2
        - name: Compile
          run: |
              ./acprep opt make
        - name: Test
          run: |
              make test
