name: run-tests

on: push

jobs:
    win:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
        - name: Setup
          uses: msys2/setup-msys2@v2
          with:
              install: >-
                  make
                  mingw-w64-x86_64-python
                  mingw-w64-x86_64-cmake
                  mingw-w64-x86_64-gcc
                  mingw-w64-x86_64-boost
        - uses: actions/checkout@v2
        - name: Compile
          run: |
              ./acprep opt make -- -DPython_ROOT_DIR=/mingw64/bin
        - name: Test
          run: |
              make test
        - name: Save Test Log
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
              name: lasttest-log
              path: Testing/Temporary/LastTest.log
